// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/auth/v1/email.proto

package v1

import (
	fmt "fmt"
	v1 "github.com/AlpacaLabs/protorepo-pagination-go/alpacalabs/pagination/v1"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmailAddress struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastModifiedAt       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	Deleted              bool                 `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Confirmed            bool                 `protobuf:"varint,6,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Primary              bool                 `protobuf:"varint,7,opt,name=primary,proto3" json:"primary,omitempty"`
	EmailAddress         string               `protobuf:"bytes,8,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	AccountId            string               `protobuf:"bytes,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EmailAddress) Reset()         { *m = EmailAddress{} }
func (m *EmailAddress) String() string { return proto.CompactTextString(m) }
func (*EmailAddress) ProtoMessage()    {}
func (*EmailAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{0}
}

func (m *EmailAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAddress.Unmarshal(m, b)
}
func (m *EmailAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAddress.Marshal(b, m, deterministic)
}
func (m *EmailAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAddress.Merge(m, src)
}
func (m *EmailAddress) XXX_Size() int {
	return xxx_messageInfo_EmailAddress.Size(m)
}
func (m *EmailAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAddress.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAddress proto.InternalMessageInfo

func (m *EmailAddress) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailAddress) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *EmailAddress) GetLastModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastModifiedAt
	}
	return nil
}

func (m *EmailAddress) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *EmailAddress) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *EmailAddress) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *EmailAddress) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

func (m *EmailAddress) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *EmailAddress) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetEmailAddressesRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEmailAddressesRequest) Reset()         { *m = GetEmailAddressesRequest{} }
func (m *GetEmailAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesRequest) ProtoMessage()    {}
func (*GetEmailAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{1}
}

func (m *GetEmailAddressesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesRequest.Merge(m, src)
}
func (m *GetEmailAddressesRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesRequest.Size(m)
}
func (m *GetEmailAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesRequest proto.InternalMessageInfo

func (m *GetEmailAddressesRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

type GetEmailAddressesResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	EmailAddresses       []*EmailAddress    `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetEmailAddressesResponse) Reset()         { *m = GetEmailAddressesResponse{} }
func (m *GetEmailAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesResponse) ProtoMessage()    {}
func (*GetEmailAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{2}
}

func (m *GetEmailAddressesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesResponse.Merge(m, src)
}
func (m *GetEmailAddressesResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesResponse.Size(m)
}
func (m *GetEmailAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesResponse proto.InternalMessageInfo

func (m *GetEmailAddressesResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetEmailAddressesResponse) GetEmailAddresses() []*EmailAddress {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

type GetEmailAddressByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmailAddressByIDRequest) Reset()         { *m = GetEmailAddressByIDRequest{} }
func (m *GetEmailAddressByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressByIDRequest) ProtoMessage()    {}
func (*GetEmailAddressByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{3}
}

func (m *GetEmailAddressByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressByIDRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressByIDRequest.Merge(m, src)
}
func (m *GetEmailAddressByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressByIDRequest.Size(m)
}
func (m *GetEmailAddressByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressByIDRequest proto.InternalMessageInfo

func (m *GetEmailAddressByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetEmailAddressByIDResponse struct {
	EmailAddress         *EmailAddress `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetEmailAddressByIDResponse) Reset()         { *m = GetEmailAddressByIDResponse{} }
func (m *GetEmailAddressByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressByIDResponse) ProtoMessage()    {}
func (*GetEmailAddressByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{4}
}

func (m *GetEmailAddressByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressByIDResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressByIDResponse.Merge(m, src)
}
func (m *GetEmailAddressByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressByIDResponse.Size(m)
}
func (m *GetEmailAddressByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressByIDResponse proto.InternalMessageInfo

func (m *GetEmailAddressByIDResponse) GetEmailAddress() *EmailAddress {
	if m != nil {
		return m.EmailAddress
	}
	return nil
}

type CreateEmailAddressRequest struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailAddressRequest) Reset()         { *m = CreateEmailAddressRequest{} }
func (m *CreateEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEmailAddressRequest) ProtoMessage()    {}
func (*CreateEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{5}
}

func (m *CreateEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailAddressRequest.Unmarshal(m, b)
}
func (m *CreateEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *CreateEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailAddressRequest.Merge(m, src)
}
func (m *CreateEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEmailAddressRequest.Size(m)
}
func (m *CreateEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailAddressRequest proto.InternalMessageInfo

func (m *CreateEmailAddressRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateEmailAddressRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type CreateAccountRequest struct {
	// Types that are valid to be assigned to AccountIdentifier:
	//	*CreateAccountRequest_EmailAddress
	//	*CreateAccountRequest_Username
	AccountIdentifier    isCreateAccountRequest_AccountIdentifier `protobuf_oneof:"account_identifier"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{6}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

type isCreateAccountRequest_AccountIdentifier interface {
	isCreateAccountRequest_AccountIdentifier()
}

type CreateAccountRequest_EmailAddress struct {
	EmailAddress string `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3,oneof"`
}

type CreateAccountRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

func (*CreateAccountRequest_EmailAddress) isCreateAccountRequest_AccountIdentifier() {}

func (*CreateAccountRequest_Username) isCreateAccountRequest_AccountIdentifier() {}

func (m *CreateAccountRequest) GetAccountIdentifier() isCreateAccountRequest_AccountIdentifier {
	if m != nil {
		return m.AccountIdentifier
	}
	return nil
}

func (m *CreateAccountRequest) GetEmailAddress() string {
	if x, ok := m.GetAccountIdentifier().(*CreateAccountRequest_EmailAddress); ok {
		return x.EmailAddress
	}
	return ""
}

func (m *CreateAccountRequest) GetUsername() string {
	if x, ok := m.GetAccountIdentifier().(*CreateAccountRequest_Username); ok {
		return x.Username
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CreateAccountRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateAccountRequest_EmailAddress)(nil),
		(*CreateAccountRequest_Username)(nil),
	}
}

type CreateEmailAddressResponse struct {
	EmailAddress         *EmailAddress `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateEmailAddressResponse) Reset()         { *m = CreateEmailAddressResponse{} }
func (m *CreateEmailAddressResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEmailAddressResponse) ProtoMessage()    {}
func (*CreateEmailAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{7}
}

func (m *CreateEmailAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailAddressResponse.Unmarshal(m, b)
}
func (m *CreateEmailAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailAddressResponse.Marshal(b, m, deterministic)
}
func (m *CreateEmailAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailAddressResponse.Merge(m, src)
}
func (m *CreateEmailAddressResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEmailAddressResponse.Size(m)
}
func (m *CreateEmailAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailAddressResponse proto.InternalMessageInfo

func (m *CreateEmailAddressResponse) GetEmailAddress() *EmailAddress {
	if m != nil {
		return m.EmailAddress
	}
	return nil
}

type ConfirmEmailAddressRequest struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,2,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailAddressRequest) Reset()         { *m = ConfirmEmailAddressRequest{} }
func (m *ConfirmEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailAddressRequest) ProtoMessage()    {}
func (*ConfirmEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{8}
}

func (m *ConfirmEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Unmarshal(m, b)
}
func (m *ConfirmEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailAddressRequest.Merge(m, src)
}
func (m *ConfirmEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Size(m)
}
func (m *ConfirmEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailAddressRequest proto.InternalMessageInfo

func (m *ConfirmEmailAddressRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *ConfirmEmailAddressRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

type UpdatePasswordRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{9}
}

func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(m, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdatePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetEmailAddressesForAccountIDRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	AccountId            string            `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEmailAddressesForAccountIDRequest) Reset()         { *m = GetEmailAddressesForAccountIDRequest{} }
func (m *GetEmailAddressesForAccountIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesForAccountIDRequest) ProtoMessage()    {}
func (*GetEmailAddressesForAccountIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{10}
}

func (m *GetEmailAddressesForAccountIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Merge(m, src)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Size(m)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesForAccountIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesForAccountIDRequest proto.InternalMessageInfo

func (m *GetEmailAddressesForAccountIDRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

func (m *GetEmailAddressesForAccountIDRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetEmailAddressesForAccountIDResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	EmailAddresses       []*EmailAddress    `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetEmailAddressesForAccountIDResponse) Reset()         { *m = GetEmailAddressesForAccountIDResponse{} }
func (m *GetEmailAddressesForAccountIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesForAccountIDResponse) ProtoMessage()    {}
func (*GetEmailAddressesForAccountIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{11}
}

func (m *GetEmailAddressesForAccountIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Merge(m, src)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Size(m)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesForAccountIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesForAccountIDResponse proto.InternalMessageInfo

func (m *GetEmailAddressesForAccountIDResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetEmailAddressesForAccountIDResponse) GetEmailAddresses() []*EmailAddress {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*EmailAddress)(nil), "alpacalabs.auth.v1.EmailAddress")
	proto.RegisterType((*GetEmailAddressesRequest)(nil), "alpacalabs.auth.v1.GetEmailAddressesRequest")
	proto.RegisterType((*GetEmailAddressesResponse)(nil), "alpacalabs.auth.v1.GetEmailAddressesResponse")
	proto.RegisterType((*GetEmailAddressByIDRequest)(nil), "alpacalabs.auth.v1.GetEmailAddressByIDRequest")
	proto.RegisterType((*GetEmailAddressByIDResponse)(nil), "alpacalabs.auth.v1.GetEmailAddressByIDResponse")
	proto.RegisterType((*CreateEmailAddressRequest)(nil), "alpacalabs.auth.v1.CreateEmailAddressRequest")
	proto.RegisterType((*CreateAccountRequest)(nil), "alpacalabs.auth.v1.CreateAccountRequest")
	proto.RegisterType((*CreateEmailAddressResponse)(nil), "alpacalabs.auth.v1.CreateEmailAddressResponse")
	proto.RegisterType((*ConfirmEmailAddressRequest)(nil), "alpacalabs.auth.v1.ConfirmEmailAddressRequest")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "alpacalabs.auth.v1.UpdatePasswordRequest")
	proto.RegisterType((*GetEmailAddressesForAccountIDRequest)(nil), "alpacalabs.auth.v1.GetEmailAddressesForAccountIDRequest")
	proto.RegisterType((*GetEmailAddressesForAccountIDResponse)(nil), "alpacalabs.auth.v1.GetEmailAddressesForAccountIDResponse")
}

func init() { proto.RegisterFile("alpacalabs/auth/v1/email.proto", fileDescriptor_6ea531f0508c5b34) }

var fileDescriptor_6ea531f0508c5b34 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xd1, 0x4e, 0x13, 0x4d,
	0x14, 0x66, 0x97, 0xff, 0x07, 0x7a, 0x0a, 0x05, 0x37, 0x68, 0x96, 0x8a, 0x5a, 0x17, 0x89, 0x4d,
	0x94, 0x69, 0x8a, 0x57, 0x7a, 0xb7, 0x2d, 0x28, 0x24, 0x68, 0x70, 0xa3, 0x24, 0x1a, 0x92, 0xcd,
	0x74, 0x67, 0x28, 0x6b, 0xba, 0x3b, 0xcb, 0xcc, 0x2c, 0x84, 0xc7, 0xf0, 0xc2, 0x17, 0xf0, 0xd2,
	0x37, 0xf0, 0x01, 0xbc, 0xf1, 0x69, 0x7c, 0x04, 0xb3, 0x3b, 0xb3, 0x74, 0x5b, 0x1a, 0x9b, 0x18,
	0x6e, 0xbc, 0xeb, 0x9c, 0xf9, 0xce, 0xf7, 0x9d, 0xf9, 0xce, 0x39, 0x5d, 0xb8, 0x8f, 0x07, 0x09,
	0x0e, 0xf0, 0x00, 0xf7, 0x44, 0x0b, 0xa7, 0xf2, 0xb4, 0x75, 0xde, 0x6e, 0xd1, 0x08, 0x87, 0x03,
	0x94, 0x70, 0x26, 0x99, 0x65, 0x0d, 0xef, 0x51, 0x76, 0x8f, 0xce, 0xdb, 0xf5, 0x07, 0x7d, 0xc6,
	0xfa, 0x03, 0xda, 0xca, 0x11, 0xbd, 0xf4, 0xa4, 0x25, 0xc3, 0x88, 0x0a, 0x89, 0xa3, 0x44, 0x25,
	0xd5, 0x37, 0x4a, 0xa4, 0x09, 0xee, 0x87, 0x31, 0x96, 0x21, 0x8b, 0x33, 0xea, 0x04, 0xf7, 0xa9,
	0x02, 0x39, 0xbf, 0x4c, 0x58, 0xdc, 0xcd, 0x94, 0x5c, 0x42, 0x38, 0x15, 0xc2, 0xaa, 0x81, 0x19,
	0x12, 0xdb, 0x68, 0x18, 0xcd, 0x8a, 0x67, 0x86, 0xc4, 0x7a, 0x0e, 0x10, 0x70, 0x8a, 0x25, 0x25,
	0x3e, 0x96, 0xb6, 0xd9, 0x30, 0x9a, 0xd5, 0xed, 0x3a, 0x52, 0xda, 0xa8, 0xd0, 0x46, 0xef, 0x0a,
	0x6d, 0xaf, 0xa2, 0xd1, 0xae, 0xb4, 0x76, 0x60, 0x65, 0x80, 0x85, 0xf4, 0x23, 0x46, 0xc2, 0x93,
	0x50, 0x11, 0xcc, 0x4e, 0x25, 0xa8, 0x65, 0x39, 0xaf, 0x75, 0x8a, 0x2b, 0x2d, 0x1b, 0xe6, 0x09,
	0x1d, 0x50, 0x49, 0x89, 0xfd, 0x5f, 0xc3, 0x68, 0x2e, 0x78, 0xc5, 0x31, 0x2b, 0x4d, 0xff, 0xcc,
	0x98, 0xff, 0x9f, 0x5e, 0x9a, 0x46, 0xbb, 0xd2, 0x5a, 0x87, 0x4a, 0xc0, 0xe2, 0x93, 0x90, 0x47,
	0x94, 0xd8, 0x73, 0x39, 0xed, 0x30, 0x90, 0x49, 0x26, 0x3c, 0x8c, 0x30, 0xbf, 0xb4, 0xe7, 0x95,
	0xa4, 0x3e, 0x5a, 0x1b, 0xb0, 0x94, 0xf7, 0xc5, 0xc7, 0xca, 0x2e, 0x7b, 0x21, 0x37, 0x6a, 0x91,
	0x96, 0x2d, 0xbc, 0x07, 0x80, 0x83, 0x80, 0xa5, 0xb1, 0xf4, 0x43, 0x62, 0x57, 0x72, 0x44, 0x45,
	0x47, 0xf6, 0x89, 0xf3, 0x09, 0xec, 0x57, 0x54, 0x96, 0x4d, 0xa7, 0xc2, 0xa3, 0x67, 0x29, 0x15,
	0xd2, 0x7a, 0x03, 0xb5, 0x20, 0xe5, 0x82, 0x71, 0x9f, 0xab, 0x48, 0xde, 0x89, 0xea, 0xf6, 0x63,
	0x54, 0x9a, 0x80, 0x61, 0x33, 0xd1, 0x79, 0x1b, 0x75, 0x73, 0xbc, 0x26, 0xf0, 0x96, 0x82, 0xf2,
	0xd1, 0xf9, 0x6e, 0xc0, 0xda, 0x04, 0x31, 0x91, 0xb0, 0x58, 0x50, 0xeb, 0x2d, 0x2c, 0x5f, 0xa9,
	0xa9, 0x90, 0x96, 0x6b, 0x4e, 0x97, 0x53, 0x78, 0xaf, 0x16, 0x8c, 0x9c, 0xad, 0x7d, 0x58, 0x1e,
	0x31, 0x88, 0x0a, 0xdb, 0x6c, 0xcc, 0x36, 0xab, 0xdb, 0x0d, 0x74, 0x7d, 0x86, 0x51, 0xb9, 0x2e,
	0xaf, 0x46, 0x47, 0xaa, 0x74, 0x9e, 0x42, 0x7d, 0xac, 0xf4, 0xce, 0xe5, 0xfe, 0x4e, 0xe1, 0xd4,
	0xd8, 0x9c, 0x3a, 0x04, 0xee, 0x4e, 0x44, 0xeb, 0xba, 0x76, 0xc7, 0x1b, 0xa7, 0x1e, 0x3a, 0xbd,
	0xaa, 0x91, 0xd6, 0x3a, 0x3e, 0xac, 0x75, 0xf3, 0xf9, 0x1e, 0xc1, 0xe8, 0x92, 0x36, 0x26, 0x69,
	0xfc, 0x79, 0x38, 0xcc, 0xf1, 0xe1, 0x38, 0x83, 0x55, 0x25, 0xe0, 0xaa, 0x50, 0xc1, 0xbd, 0x39,
	0x91, 0x7b, 0x6f, 0x66, 0x8c, 0x7d, 0x1d, 0x16, 0x52, 0x41, 0x79, 0x8c, 0x23, 0xaa, 0xb8, 0xf7,
	0x66, 0xbc, 0xab, 0x48, 0x67, 0x15, 0xac, 0xa1, 0x36, 0x8d, 0x65, 0xb6, 0x62, 0xdc, 0x09, 0xa0,
	0x3e, 0xe9, 0x4d, 0x37, 0x6b, 0x5c, 0x0c, 0xf5, 0xae, 0xda, 0xaf, 0xbf, 0x76, 0xee, 0x09, 0xdc,
	0xd2, 0x2b, 0x9a, 0x0f, 0xa3, 0x1f, 0x30, 0xa2, 0x1f, 0xe9, 0xad, 0x94, 0x2f, 0xba, 0x8c, 0x50,
	0xe7, 0x03, 0xdc, 0x7e, 0x9f, 0x10, 0x2c, 0xe9, 0x21, 0x16, 0xe2, 0x82, 0x71, 0x52, 0x48, 0x8d,
	0xfa, 0x6f, 0x8c, 0xf9, 0x6f, 0x3d, 0x84, 0xc5, 0x98, 0x5e, 0xf8, 0x89, 0xce, 0xd2, 0xfc, 0xd5,
	0x98, 0x5e, 0x14, 0x44, 0xce, 0x17, 0x03, 0x1e, 0x5d, 0xdb, 0xa9, 0x97, 0x8c, 0xeb, 0x8e, 0x0d,
	0x47, 0xf4, 0x86, 0x97, 0x79, 0xda, 0xe8, 0xfc, 0x30, 0x60, 0x73, 0x4a, 0x5d, 0xff, 0xc2, 0xde,
	0x77, 0x3e, 0x1b, 0x70, 0x27, 0x60, 0xd1, 0x84, 0xbc, 0x4e, 0xc5, 0x4d, 0xe5, 0xe9, 0x61, 0xf6,
	0xcf, 0x7e, 0x68, 0x7c, 0x7c, 0xd1, 0x0f, 0xe5, 0x69, 0xda, 0x43, 0x01, 0x8b, 0x5a, 0x6e, 0x8e,
	0x3d, 0xc8, 0x3f, 0x75, 0xd9, 0x35, 0xa7, 0x09, 0xdb, 0xca, 0xb2, 0xb6, 0xfa, 0xac, 0x75, 0xfd,
	0xe3, 0xfa, 0xd5, 0x9c, 0x75, 0x0f, 0xdc, 0x6f, 0xa6, 0x35, 0xcc, 0x43, 0x19, 0x35, 0x3a, 0x6a,
	0xff, 0x2c, 0x07, 0x8f, 0xb3, 0xe0, 0xf1, 0x51, 0xbb, 0x37, 0x97, 0xb3, 0x3e, 0xfb, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x44, 0xaa, 0x5b, 0x44, 0xa9, 0x07, 0x00, 0x00,
}
