// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/auth/v1/email.proto

package v1

import (
	fmt "fmt"
	v1 "github.com/AlpacaLabs/protorepo-pagination-go/alpacalabs/pagination/v1"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmailAddress struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastModifiedAt       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	Deleted              bool                 `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Confirmed            bool                 `protobuf:"varint,6,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Primary              bool                 `protobuf:"varint,7,opt,name=primary,proto3" json:"primary,omitempty"`
	EmailAddress         string               `protobuf:"bytes,8,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	AccountId            string               `protobuf:"bytes,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EmailAddress) Reset()         { *m = EmailAddress{} }
func (m *EmailAddress) String() string { return proto.CompactTextString(m) }
func (*EmailAddress) ProtoMessage()    {}
func (*EmailAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{0}
}

func (m *EmailAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAddress.Unmarshal(m, b)
}
func (m *EmailAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAddress.Marshal(b, m, deterministic)
}
func (m *EmailAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAddress.Merge(m, src)
}
func (m *EmailAddress) XXX_Size() int {
	return xxx_messageInfo_EmailAddress.Size(m)
}
func (m *EmailAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAddress.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAddress proto.InternalMessageInfo

func (m *EmailAddress) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailAddress) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *EmailAddress) GetLastModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastModifiedAt
	}
	return nil
}

func (m *EmailAddress) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *EmailAddress) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *EmailAddress) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *EmailAddress) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

func (m *EmailAddress) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *EmailAddress) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetEmailAddressesRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEmailAddressesRequest) Reset()         { *m = GetEmailAddressesRequest{} }
func (m *GetEmailAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesRequest) ProtoMessage()    {}
func (*GetEmailAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{1}
}

func (m *GetEmailAddressesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesRequest.Merge(m, src)
}
func (m *GetEmailAddressesRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesRequest.Size(m)
}
func (m *GetEmailAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesRequest proto.InternalMessageInfo

func (m *GetEmailAddressesRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

type GetEmailAddressesResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	EmailAddresses       []*EmailAddress    `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetEmailAddressesResponse) Reset()         { *m = GetEmailAddressesResponse{} }
func (m *GetEmailAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesResponse) ProtoMessage()    {}
func (*GetEmailAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{2}
}

func (m *GetEmailAddressesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesResponse.Merge(m, src)
}
func (m *GetEmailAddressesResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesResponse.Size(m)
}
func (m *GetEmailAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesResponse proto.InternalMessageInfo

func (m *GetEmailAddressesResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetEmailAddressesResponse) GetEmailAddresses() []*EmailAddress {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetEmailAddressesForAccountIDRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	AccountId            string            `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEmailAddressesForAccountIDRequest) Reset()         { *m = GetEmailAddressesForAccountIDRequest{} }
func (m *GetEmailAddressesForAccountIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesForAccountIDRequest) ProtoMessage()    {}
func (*GetEmailAddressesForAccountIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{3}
}

func (m *GetEmailAddressesForAccountIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Merge(m, src)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Size(m)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesForAccountIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesForAccountIDRequest proto.InternalMessageInfo

func (m *GetEmailAddressesForAccountIDRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

func (m *GetEmailAddressesForAccountIDRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetEmailAddressesForAccountIDResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	EmailAddresses       []*EmailAddress    `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetEmailAddressesForAccountIDResponse) Reset()         { *m = GetEmailAddressesForAccountIDResponse{} }
func (m *GetEmailAddressesForAccountIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesForAccountIDResponse) ProtoMessage()    {}
func (*GetEmailAddressesForAccountIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ea531f0508c5b34, []int{4}
}

func (m *GetEmailAddressesForAccountIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Merge(m, src)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Size(m)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesForAccountIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesForAccountIDResponse proto.InternalMessageInfo

func (m *GetEmailAddressesForAccountIDResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetEmailAddressesForAccountIDResponse) GetEmailAddresses() []*EmailAddress {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*EmailAddress)(nil), "alpacalabs.auth.v1.EmailAddress")
	proto.RegisterType((*GetEmailAddressesRequest)(nil), "alpacalabs.auth.v1.GetEmailAddressesRequest")
	proto.RegisterType((*GetEmailAddressesResponse)(nil), "alpacalabs.auth.v1.GetEmailAddressesResponse")
	proto.RegisterType((*GetEmailAddressesForAccountIDRequest)(nil), "alpacalabs.auth.v1.GetEmailAddressesForAccountIDRequest")
	proto.RegisterType((*GetEmailAddressesForAccountIDResponse)(nil), "alpacalabs.auth.v1.GetEmailAddressesForAccountIDResponse")
}

func init() { proto.RegisterFile("alpacalabs/auth/v1/email.proto", fileDescriptor_6ea531f0508c5b34) }

var fileDescriptor_6ea531f0508c5b34 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0x9d, 0xef, 0x6b, 0xeb, 0x49, 0x9b, 0xa2, 0x59, 0x20, 0x13, 0xf1, 0x13, 0xa5, 0x20,
	0xb2, 0xe9, 0x58, 0x09, 0x2b, 0xd8, 0xb9, 0x14, 0x50, 0xa5, 0x82, 0x8a, 0x85, 0xba, 0x40, 0x95,
	0xa2, 0xc9, 0xcc, 0x8d, 0x33, 0xc8, 0xce, 0x98, 0x99, 0x71, 0x24, 0x1e, 0x83, 0x05, 0x2f, 0xc0,
	0x92, 0x37, 0xe0, 0x01, 0xd8, 0xf0, 0x34, 0x3c, 0x02, 0x9a, 0xb1, 0x43, 0x9c, 0xa6, 0x52, 0x56,
	0x2c, 0xd8, 0xf9, 0xde, 0x39, 0xf7, 0x9c, 0xa3, 0x73, 0xc7, 0x83, 0xee, 0xd3, 0xac, 0xa0, 0x8c,
	0x66, 0x74, 0xa2, 0x23, 0x5a, 0x9a, 0x59, 0xb4, 0x18, 0x46, 0x90, 0x53, 0x91, 0x91, 0x42, 0x49,
	0x23, 0x31, 0x5e, 0x9d, 0x13, 0x7b, 0x4e, 0x16, 0xc3, 0xee, 0x83, 0x54, 0xca, 0x34, 0x83, 0xc8,
	0x21, 0x26, 0xe5, 0x34, 0x32, 0x22, 0x07, 0x6d, 0x68, 0x5e, 0x54, 0x43, 0xdd, 0xa3, 0x06, 0x69,
	0x41, 0x53, 0x31, 0xa7, 0x46, 0xc8, 0xb9, 0xa5, 0x2e, 0x68, 0x0a, 0x15, 0xa8, 0xff, 0xcb, 0x47,
	0xfb, 0x2f, 0xac, 0x52, 0xcc, 0xb9, 0x02, 0xad, 0x71, 0x07, 0xf9, 0x82, 0x87, 0x5e, 0xcf, 0x1b,
	0x04, 0x89, 0x2f, 0x38, 0x7e, 0x8a, 0x10, 0x53, 0x40, 0x0d, 0xf0, 0x31, 0x35, 0xa1, 0xdf, 0xf3,
	0x06, 0xed, 0x51, 0x97, 0x54, 0xda, 0x64, 0xa9, 0x4d, 0xde, 0x2d, 0xb5, 0x93, 0xa0, 0x46, 0xc7,
	0x06, 0x9f, 0xa2, 0x5b, 0x19, 0xd5, 0x66, 0x9c, 0x4b, 0x2e, 0xa6, 0xa2, 0x22, 0x68, 0x6d, 0x25,
	0xe8, 0xd8, 0x99, 0xd7, 0xf5, 0x48, 0x6c, 0x70, 0x88, 0x76, 0x39, 0x64, 0x60, 0x80, 0x87, 0xff,
	0xf5, 0xbc, 0xc1, 0x5e, 0xb2, 0x2c, 0xad, 0xb5, 0xfa, 0xd3, 0x32, 0xff, 0xbf, 0xdd, 0x5a, 0x8d,
	0x8e, 0x0d, 0xbe, 0x8b, 0x02, 0x26, 0xe7, 0x53, 0xa1, 0x72, 0xe0, 0xe1, 0x8e, 0xa3, 0x5d, 0x35,
	0xac, 0x64, 0xa1, 0x44, 0x4e, 0xd5, 0xa7, 0x70, 0xb7, 0x92, 0xac, 0x4b, 0x7c, 0x84, 0x0e, 0xdc,
	0x5e, 0xc6, 0xb4, 0x8a, 0x2b, 0xdc, 0x73, 0x41, 0xed, 0x43, 0x33, 0xc2, 0x7b, 0x08, 0x51, 0xc6,
	0x64, 0x39, 0x37, 0x63, 0xc1, 0xc3, 0xc0, 0x21, 0x82, 0xba, 0x73, 0xc6, 0xfb, 0x1f, 0x50, 0xf8,
	0x0a, 0x4c, 0x33, 0x74, 0xd0, 0x09, 0x7c, 0x2c, 0x41, 0x1b, 0xfc, 0x06, 0x75, 0x58, 0xa9, 0xb4,
	0x54, 0x63, 0x55, 0x75, 0xdc, 0x26, 0xda, 0xa3, 0xc7, 0xa4, 0x71, 0x03, 0x56, 0xcb, 0x24, 0x8b,
	0x21, 0x79, 0xee, 0xf0, 0x35, 0x41, 0x72, 0xc0, 0x9a, 0x65, 0xff, 0xbb, 0x87, 0xee, 0xdc, 0x20,
	0xa6, 0x0b, 0x39, 0xd7, 0x80, 0xdf, 0xa2, 0xc3, 0x3f, 0x6a, 0x55, 0xab, 0x96, 0x1b, 0x6c, 0x97,
	0xab, 0xf0, 0x49, 0x87, 0xad, 0xd5, 0xf8, 0x0c, 0x1d, 0xae, 0x05, 0x04, 0x3a, 0xf4, 0x7b, 0xad,
	0x41, 0x7b, 0xd4, 0x23, 0x9b, 0x77, 0x98, 0x34, 0x7d, 0x25, 0x1d, 0x58, 0x73, 0xd9, 0xff, 0xe2,
	0xa1, 0x87, 0x1b, 0xde, 0x5f, 0x4a, 0x15, 0xd7, 0x49, 0x9e, 0xfe, 0xa5, 0xd0, 0xae, 0xed, 0xcf,
	0xbf, 0xbe, 0xbf, 0x1f, 0x1e, 0x7a, 0xb4, 0xc5, 0xd7, 0xbf, 0x90, 0xef, 0xc9, 0x67, 0x0f, 0xdd,
	0x66, 0x32, 0xbf, 0x61, 0xee, 0x24, 0x88, 0x4b, 0x33, 0xbb, 0xb0, 0x7f, 0xd0, 0x85, 0xf7, 0xfe,
	0x59, 0x2a, 0xcc, 0xac, 0x9c, 0x10, 0x26, 0xf3, 0x28, 0x76, 0xd8, 0x73, 0xf7, 0xa4, 0xd8, 0x63,
	0x05, 0x85, 0x3c, 0xb6, 0x53, 0xc7, 0xa9, 0x8c, 0x36, 0x1f, 0xb1, 0xaf, 0x7e, 0x2b, 0x3e, 0x8f,
	0xbf, 0xf9, 0x78, 0x35, 0x47, 0x2c, 0x35, 0xb9, 0x1c, 0xfe, 0x6c, 0x36, 0xaf, 0x6c, 0xf3, 0xea,
	0x72, 0x38, 0xd9, 0x71, 0xac, 0x4f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xb4, 0x78, 0x68,
	0x11, 0x05, 0x00, 0x00,
}
