// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/auth/v1/password_reset.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResetPasswordRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	EmailAddress         string   `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_793b66ac1a4c5cd8, []int{0}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResetPasswordRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_793b66ac1a4c5cd8, []int{1}
}

func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(m, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

type PasswordResetCode struct {
	// a randomly generated reset code
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// indicates whether a password reset code has been used. Used codes are necessarily unusable.
	Used bool `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	// if true, this password reset code cannot be used. When a user uses a reset code,
	// all previously issued codes are rendered stale.
	Stale bool `protobuf:"varint,3,opt,name=stale,proto3" json:"stale,omitempty"`
	// when the reset code expires
	ExpiresAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// the account to which this code belongs
	AccountId            string   `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordResetCode) Reset()         { *m = PasswordResetCode{} }
func (m *PasswordResetCode) String() string { return proto.CompactTextString(m) }
func (*PasswordResetCode) ProtoMessage()    {}
func (*PasswordResetCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_793b66ac1a4c5cd8, []int{2}
}

func (m *PasswordResetCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResetCode.Unmarshal(m, b)
}
func (m *PasswordResetCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResetCode.Marshal(b, m, deterministic)
}
func (m *PasswordResetCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResetCode.Merge(m, src)
}
func (m *PasswordResetCode) XXX_Size() int {
	return xxx_messageInfo_PasswordResetCode.Size(m)
}
func (m *PasswordResetCode) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResetCode.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResetCode proto.InternalMessageInfo

func (m *PasswordResetCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PasswordResetCode) GetUsed() bool {
	if m != nil {
		return m.Used
	}
	return false
}

func (m *PasswordResetCode) GetStale() bool {
	if m != nil {
		return m.Stale
	}
	return false
}

func (m *PasswordResetCode) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *PasswordResetCode) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetCodeOptionsRequest struct {
	// Types that are valid to be assigned to Account:
	//	*GetCodeOptionsRequest_EmailAddress
	//	*GetCodeOptionsRequest_PhoneNumber
	//	*GetCodeOptionsRequest_Username
	Account              isGetCodeOptionsRequest_Account `protobuf_oneof:"account"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GetCodeOptionsRequest) Reset()         { *m = GetCodeOptionsRequest{} }
func (m *GetCodeOptionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCodeOptionsRequest) ProtoMessage()    {}
func (*GetCodeOptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_793b66ac1a4c5cd8, []int{3}
}

func (m *GetCodeOptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCodeOptionsRequest.Unmarshal(m, b)
}
func (m *GetCodeOptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCodeOptionsRequest.Marshal(b, m, deterministic)
}
func (m *GetCodeOptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCodeOptionsRequest.Merge(m, src)
}
func (m *GetCodeOptionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCodeOptionsRequest.Size(m)
}
func (m *GetCodeOptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCodeOptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCodeOptionsRequest proto.InternalMessageInfo

type isGetCodeOptionsRequest_Account interface {
	isGetCodeOptionsRequest_Account()
}

type GetCodeOptionsRequest_EmailAddress struct {
	EmailAddress string `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3,oneof"`
}

type GetCodeOptionsRequest_PhoneNumber struct {
	PhoneNumber string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3,oneof"`
}

type GetCodeOptionsRequest_Username struct {
	Username string `protobuf:"bytes,3,opt,name=username,proto3,oneof"`
}

func (*GetCodeOptionsRequest_EmailAddress) isGetCodeOptionsRequest_Account() {}

func (*GetCodeOptionsRequest_PhoneNumber) isGetCodeOptionsRequest_Account() {}

func (*GetCodeOptionsRequest_Username) isGetCodeOptionsRequest_Account() {}

func (m *GetCodeOptionsRequest) GetAccount() isGetCodeOptionsRequest_Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *GetCodeOptionsRequest) GetEmailAddress() string {
	if x, ok := m.GetAccount().(*GetCodeOptionsRequest_EmailAddress); ok {
		return x.EmailAddress
	}
	return ""
}

func (m *GetCodeOptionsRequest) GetPhoneNumber() string {
	if x, ok := m.GetAccount().(*GetCodeOptionsRequest_PhoneNumber); ok {
		return x.PhoneNumber
	}
	return ""
}

func (m *GetCodeOptionsRequest) GetUsername() string {
	if x, ok := m.GetAccount().(*GetCodeOptionsRequest_Username); ok {
		return x.Username
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetCodeOptionsRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetCodeOptionsRequest_EmailAddress)(nil),
		(*GetCodeOptionsRequest_PhoneNumber)(nil),
		(*GetCodeOptionsRequest_Username)(nil),
	}
}

type GetCodeOptionsResponse struct {
	CodeOptions          *CodeOptions `protobuf:"bytes,1,opt,name=code_options,json=codeOptions,proto3" json:"code_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetCodeOptionsResponse) Reset()         { *m = GetCodeOptionsResponse{} }
func (m *GetCodeOptionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCodeOptionsResponse) ProtoMessage()    {}
func (*GetCodeOptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_793b66ac1a4c5cd8, []int{4}
}

func (m *GetCodeOptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCodeOptionsResponse.Unmarshal(m, b)
}
func (m *GetCodeOptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCodeOptionsResponse.Marshal(b, m, deterministic)
}
func (m *GetCodeOptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCodeOptionsResponse.Merge(m, src)
}
func (m *GetCodeOptionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCodeOptionsResponse.Size(m)
}
func (m *GetCodeOptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCodeOptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCodeOptionsResponse proto.InternalMessageInfo

func (m *GetCodeOptionsResponse) GetCodeOptions() *CodeOptions {
	if m != nil {
		return m.CodeOptions
	}
	return nil
}

type PhoneNumber struct {
	// primary key
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// account the phone number belongs to
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// actual value
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_793b66ac1a4c5cd8, []int{5}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PhoneNumber) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *PhoneNumber) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type EmailAddress struct {
	// primary key
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// account the phone number belongs to
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// actual value
	EmailAddress         string   `protobuf:"bytes,3,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailAddress) Reset()         { *m = EmailAddress{} }
func (m *EmailAddress) String() string { return proto.CompactTextString(m) }
func (*EmailAddress) ProtoMessage()    {}
func (*EmailAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_793b66ac1a4c5cd8, []int{6}
}

func (m *EmailAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAddress.Unmarshal(m, b)
}
func (m *EmailAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAddress.Marshal(b, m, deterministic)
}
func (m *EmailAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAddress.Merge(m, src)
}
func (m *EmailAddress) XXX_Size() int {
	return xxx_messageInfo_EmailAddress.Size(m)
}
func (m *EmailAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAddress.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAddress proto.InternalMessageInfo

func (m *EmailAddress) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailAddress) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *EmailAddress) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type CodeOptions struct {
	PhoneNumbers         []*PhoneNumber  `protobuf:"bytes,1,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	EmailAddresses       []*EmailAddress `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CodeOptions) Reset()         { *m = CodeOptions{} }
func (m *CodeOptions) String() string { return proto.CompactTextString(m) }
func (*CodeOptions) ProtoMessage()    {}
func (*CodeOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_793b66ac1a4c5cd8, []int{7}
}

func (m *CodeOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeOptions.Unmarshal(m, b)
}
func (m *CodeOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeOptions.Marshal(b, m, deterministic)
}
func (m *CodeOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeOptions.Merge(m, src)
}
func (m *CodeOptions) XXX_Size() int {
	return xxx_messageInfo_CodeOptions.Size(m)
}
func (m *CodeOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CodeOptions proto.InternalMessageInfo

func (m *CodeOptions) GetPhoneNumbers() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func (m *CodeOptions) GetEmailAddresses() []*EmailAddress {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*ResetPasswordRequest)(nil), "alpacalabs.auth.v1.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "alpacalabs.auth.v1.ResetPasswordResponse")
	proto.RegisterType((*PasswordResetCode)(nil), "alpacalabs.auth.v1.PasswordResetCode")
	proto.RegisterType((*GetCodeOptionsRequest)(nil), "alpacalabs.auth.v1.GetCodeOptionsRequest")
	proto.RegisterType((*GetCodeOptionsResponse)(nil), "alpacalabs.auth.v1.GetCodeOptionsResponse")
	proto.RegisterType((*PhoneNumber)(nil), "alpacalabs.auth.v1.PhoneNumber")
	proto.RegisterType((*EmailAddress)(nil), "alpacalabs.auth.v1.EmailAddress")
	proto.RegisterType((*CodeOptions)(nil), "alpacalabs.auth.v1.CodeOptions")
}

func init() {
	proto.RegisterFile("alpacalabs/auth/v1/password_reset.proto", fileDescriptor_793b66ac1a4c5cd8)
}

var fileDescriptor_793b66ac1a4c5cd8 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x6e, 0xd3, 0x4a,
	0x14, 0xc6, 0x6b, 0x27, 0xbd, 0x37, 0x39, 0x76, 0x8b, 0x18, 0xb5, 0x25, 0xaa, 0x40, 0x0d, 0xae,
	0x10, 0xdd, 0xd4, 0x56, 0xca, 0x0a, 0x76, 0x0e, 0x20, 0x5a, 0xa9, 0x82, 0xc8, 0x42, 0x5d, 0xa0,
	0x48, 0xd6, 0xd8, 0x3e, 0x24, 0x96, 0x62, 0x8f, 0xf1, 0x8c, 0x1b, 0x1e, 0x82, 0x0d, 0x2f, 0xc0,
	0x82, 0x25, 0xbc, 0x09, 0x4f, 0x85, 0x66, 0xec, 0x90, 0xa9, 0x13, 0x16, 0xec, 0x66, 0xbe, 0x9c,
	0x3f, 0xdf, 0xf9, 0xe5, 0x78, 0xe0, 0x29, 0x5d, 0x14, 0x34, 0xa6, 0x0b, 0x1a, 0x71, 0x8f, 0x56,
	0x62, 0xee, 0xdd, 0x8e, 0xbc, 0x82, 0x72, 0xbe, 0x64, 0x65, 0x12, 0x96, 0xc8, 0x51, 0xb8, 0x45,
	0xc9, 0x04, 0x23, 0x64, 0x1d, 0xe8, 0xca, 0x40, 0xf7, 0x76, 0x74, 0x7c, 0x32, 0x63, 0x6c, 0xb6,
	0x40, 0x4f, 0x45, 0x44, 0xd5, 0x47, 0x4f, 0xa4, 0x19, 0x72, 0x41, 0xb3, 0xa2, 0x4e, 0x72, 0x4a,
	0x38, 0x08, 0x64, 0x8d, 0x49, 0x53, 0x31, 0xc0, 0x4f, 0x15, 0x72, 0x41, 0x08, 0x74, 0x63, 0x96,
	0xe0, 0xc0, 0x18, 0x1a, 0x67, 0xfd, 0x40, 0x9d, 0xc9, 0x29, 0xec, 0x61, 0x46, 0xd3, 0x45, 0x48,
	0x93, 0xa4, 0x44, 0xce, 0x07, 0xa6, 0xfa, 0xd1, 0x56, 0xa2, 0x5f, 0x6b, 0xe4, 0x31, 0xd8, 0x39,
	0x2e, 0xc3, 0x95, 0xc3, 0x41, 0x47, 0xc5, 0x58, 0x39, 0x2e, 0x57, 0x2d, 0x9c, 0x07, 0x70, 0xd8,
	0xea, 0xc9, 0x0b, 0x96, 0x73, 0x74, 0x7e, 0x1a, 0x70, 0x5f, 0x13, 0x51, 0xbc, 0x94, 0x6d, 0xb7,
	0x59, 0x21, 0xd0, 0xad, 0x38, 0x26, 0xca, 0x41, 0x2f, 0x50, 0x67, 0x72, 0x00, 0xbb, 0x5c, 0xd0,
	0x05, 0xaa, 0x96, 0xbd, 0xa0, 0xbe, 0x90, 0xe7, 0x00, 0xf8, 0xb9, 0x48, 0x4b, 0xe4, 0x21, 0x15,
	0x83, 0xee, 0xd0, 0x38, 0xb3, 0x2e, 0x8e, 0xdd, 0x1a, 0x8b, 0xbb, 0xc2, 0xe2, 0xbe, 0x5f, 0x61,
	0x09, 0xfa, 0x4d, 0xb4, 0x2f, 0xc8, 0x23, 0x00, 0x1a, 0xc7, 0xac, 0xca, 0x45, 0x98, 0x26, 0x83,
	0x5d, 0xd5, 0xbe, 0xdf, 0x28, 0x57, 0x89, 0xf3, 0xc5, 0x80, 0xc3, 0x37, 0xb5, 0xc7, 0x77, 0x85,
	0x48, 0x59, 0xce, 0x57, 0xf0, 0x9e, 0xb4, 0x41, 0x29, 0xeb, 0x97, 0x3b, 0x2d, 0x54, 0xa7, 0x60,
	0x17, 0x73, 0x96, 0x63, 0x98, 0x57, 0x59, 0x84, 0x65, 0x8d, 0xf3, 0x72, 0x27, 0xb0, 0x94, 0xfa,
	0x56, 0x89, 0xe4, 0x21, 0xf4, 0x2a, 0x8e, 0x65, 0x4e, 0xb3, 0x7a, 0x30, 0x19, 0xf0, 0x47, 0x19,
	0xf7, 0xe1, 0xff, 0xc6, 0x90, 0x33, 0x85, 0xa3, 0xb6, 0x9b, 0x1a, 0x2b, 0x19, 0x83, 0x2d, 0xa1,
	0x85, 0xac, 0xd6, 0x95, 0x1b, 0xeb, 0xe2, 0xc4, 0xdd, 0xdc, 0x17, 0x57, 0x4f, 0xb7, 0xe2, 0xf5,
	0xc5, 0x09, 0xc1, 0x9a, 0x68, 0xae, 0xf6, 0xc1, 0x4c, 0x93, 0xe6, 0x1f, 0x31, 0xd3, 0xa4, 0x85,
	0xca, 0x6c, 0xa1, 0x92, 0x4b, 0x71, 0x67, 0xd2, 0x66, 0x29, 0xb4, 0x39, 0x9d, 0x08, 0xec, 0xd7,
	0x3a, 0x9c, 0x7f, 0xec, 0xb0, 0xb1, 0x9b, 0x9d, 0xcd, 0xdd, 0x74, 0xbe, 0x19, 0x60, 0x69, 0x13,
	0x92, 0x57, 0xb0, 0xa7, 0xdb, 0x92, 0x64, 0x3a, 0x7f, 0x23, 0xa3, 0x4d, 0x1f, 0xd8, 0x9a, 0x71,
	0x4e, 0xae, 0xe0, 0xde, 0x9d, 0xd6, 0x28, 0x3f, 0x0c, 0x59, 0x67, 0xb8, 0xad, 0x8e, 0x3e, 0x64,
	0xb0, 0xaf, 0xdb, 0x43, 0x3e, 0xfe, 0x6a, 0xc0, 0x51, 0xcc, 0xb2, 0x2d, 0x79, 0xe3, 0xbe, 0x5f,
	0x89, 0xf9, 0x44, 0xee, 0xeb, 0xc4, 0xf8, 0xf0, 0x62, 0x96, 0x8a, 0x79, 0x15, 0xb9, 0x31, 0xcb,
	0x3c, 0x5f, 0xc5, 0x5e, 0xcb, 0xe7, 0x41, 0xad, 0x73, 0x89, 0x05, 0x3b, 0x97, 0x59, 0xe7, 0x33,
	0xe6, 0x6d, 0xbe, 0x1d, 0xdf, 0xcd, 0x8e, 0x7f, 0xed, 0xff, 0x30, 0xc9, 0x3a, 0xcf, 0x95, 0xa5,
	0xdd, 0x9b, 0xd1, 0x2f, 0x5d, 0x9c, 0x4a, 0x71, 0x7a, 0x33, 0x8a, 0xfe, 0x53, 0x55, 0x9f, 0xfd,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0x35, 0x8d, 0x9b, 0xb2, 0x88, 0x04, 0x00, 0x00,
}
